ingress:
  # Public address for the ingress VM
  address: "1.2.3.4"  
  # Ubuntu flavor for the ingress VM
  ubuntu: bionic

minio:
  # Configuration on the ingress VM for this service.
  ingress_config:
    name: minio
    server_name: minio.example.org
    proxy_pass: http://localhost:9000

    # Nginx reverse proxy conf
    opt:
      global: []
        # - "ignore_invalid_headers off;"
        # - "client_max_body_size 0;"
        # - "proxy_buffering off;"
      paths: {}
        # /:
        #   - "proxy_set_header X-Real-IP $remote_addr;"
        #   - "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;"
        #   - "proxy_set_header X-Forwarded-Proto $scheme;"
        #   - "proxy_set_header Host $http_host;"
        #   - "proxy_connect_timeout 300;"
        #   - "proxy_http_version 1.1;"
        #   - "proxy_set_header Connection \"\";"
        #   - "chunked_transfer_encoding off;"
    
    # Auto TLS
    tls:
      enabled: true
      email: foo@example.org

  # Configuration to connect from tunnel VM to ingress VM
  tunnel:
    source: "127.0.0.1:9000"
    destination: "192.168.88.21:9000"
    
