---
- name: install_mole
  copy:
    src: mole
    dest: /usr/local/bin/mole
    mode: '0744'

- name: render_start_script
  template:
    src: start-mole.sh
    dest: /usr/local/bin/start-mole
    mode: '0744'

- name: install_service_file
  copy:
    src: mole.service
    dest: /etc/systemd/system/mole.service
    mode: '0644'

- name: start_mole_service
  systemd:
    name: mole
    state: restarted
    daemon-reload: yes