---
docker:
  gpg: https://download.docker.com/linux/ubuntu/gpg
  apt: http://mirrors.aliyun.com/docker-ce/linux/ubuntu
  compose: https://get.daocloud.io/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
  accelerator: ""