---
- name: install_software
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - certbot
    - python-certbot-nginx

- name: configure_minio_nginx
  when: ingress.minio.enabled
  template:
    src: minio.conf.j2
    dest: /etc/nginx/conf.d/minio.conf
  notify:
    - restart_nginx

- name: configure_minio_cert
  when: ingress.minio.enabled
  command:
    cmd: certbot --nginx -d {{ ingress.minio.host }} -m {{ ingress.tls.email }} --agree-tos -n

- name: configure_tls_auto_renew
  cron:
    name: renew_tls
    hour: "12"
    minute: "0"
    job: "/usr/bin/certbot renew --quiet"
    state: present